### ISSUE TITLE
Errors in baxos.

### ISSUE THREAD

**Issue by changtong9** [Visa-Research/volepsi#81] opened 2024-12-12 06:55 UTC
When the decode key size is larger than the key size used in encode, it will output wrong decode results with a high probability, just like this. I think both zero and collisions are wrong decode results, and it seems this will not affect the correctness of psi, due to the existence of VOLE.
<img width="645" alt="2024-12-12 14 40 19" src="https://github.com/user-attachments/assets/da4dc478-077f-4106-b9cc-27dfa3e93a1c" />

BTW, what's the main difference between baxos and paxos.

**Comment by ladnir** [comment] 2024-12-12 07:05
Can you share code that reproduces the error? Baxos in the binning optimization. Just a different okvs scheme

**Comment by changtong9** [comment] 2024-12-12 07:12
Just a simple test can reproduce the error.

	paxos.solve<block>(items, values, p);
	std::vector<block> test1(items);
	test1.insert(test1.end(), tmp.begin(), tmp.end());
	std::vector<block> test2(test1.size());
	paxos.decode<block>(test1, test2, p);
	for (u64 i = 0; i < test2.size(); ++i) {
		std::cout << "the " << i << "-th key is " << test1[i] << " value is " << test2[i] << std::endl;
	}

**Comment by ladnir** [comment] 2024-12-23 03:27
im failing to reproduce. Can you share a full working example?

**Comment by changtong9** [comment] 2024-12-23 05:55
I modified the `Baxos_solve_Test` in Paxos_Tests.cpp.

```
void Baxos_solve_Test(const oc::CLP& cmd)
{

	u64 n = cmd.getOr("n", 1ull << cmd.getOr("nn", 4));
	u64 b = cmd.getOr("b", n/4);
	u64 w = cmd.getOr("w", 3);
	u64 s = cmd.getOr("s", 0);
	//u64 v = cmd.getOr("v", cmd.isSet("v") ? 1 : 0);
	u64 t = cmd.getOr("t", 1);
	bool v = cmd.isSet("v");
	//u64 g = cmd.getOr("g", 3);

	//for (u64 n = 10; n < nn; ++n)
	{
		PRNG prng(block(0, s));
		Baxos paxos;
		paxos.init(n, b, w, 40, PaxosParam::GF128, prng.get<block>());

		std::vector<block> items(n), values(n), tmp(n), values2(n), p(paxos.size());
		prng.get(items.data(), items.size());
		prng.get(values.data(), values.size());
		prng.get(tmp.data(), tmp.size());

		for (u64 tt = 0; tt < t; ++tt)
		{
			PRNG prng(block(tt, s));
			paxos.init(n, b, w, 40, PaxosParam::GF128, prng.get<block>());

			paxos.solve<block>(items, values, p);
			std::vector<block> test1(items);
			test1.insert(test1.end(), tmp.begin(), tmp.end());
			std::vector<block> test2(test1.size());
			paxos.decode<block>(test1, test2, p);
			for (u64 i = 0; i < test2.size(); ++i) {
				std::cout <<"the " << i << "-th key is " << test1[i] << " value is " << test2[i] << std::endl;
			}
			paxos.decode<block>(items, values2, p);

			if (v)
				std::cout << "." << std::flush;
			if (values2 != values)
			{
				u64 count = 0;
				for (u64 i = 0; i < n; ++i)
				{
					if (values[i] != values2[i])
					{
						if (count < 10)
							std::cout << i << " " << values[i] << " " << values2[i] << std::endl;
						else
						{

							std::cout << "..." << std::endl;
							break;
						}

						++count;
					}
				}

				std::cout << "seed " << prng.getSeed() << " "<<tt << std::endl;
				throw RTE_LOC;
			}
		}
	}

}
```

**Comment by ladnir** [comment] 2024-12-23 19:41
that is the correct behavior. there is not issue with that test. In what way is it not behaving as you expected.

**Comment by changtong9** [comment] 2024-12-24 02:24
I have modified the test in `paxos.decode`. The first half of `test1` is the same as `items` and the second half is filled with randomness. It is expected that the `decode` result of the second half is some random number, but it outputs zero and collision values, as the pic above.

**Comment by ladnir** [comment] 2024-12-24 02:58
Your expectation is incorrect. Random values will return some value but no guarantee on what. So what is happening internally?

Each input x is mapped to 3 position p0, p1, p2. The output of x is typically just E[p0] + E[p1] + E[p2]. Sometime the "dense columns" are used but this isn't typically. 

Many of these E[i] positions will be zero. Especially when the input set is small. Therefore it's somewhat likely the output will be the same.

As the input set gets larger, this is less likely. You can also random the okvs by filling the zeros positions with random values. Do this by passing a prng to solve(...). 

But if you are relaying on the fact that other outputs are actually random, that's a bad idea. You can't depend on decode(x) to be random in general because decode will be a linear function and therefore have linear correlations.

**Comment by changtong9** [comment] 2024-12-24 08:11
Thanks for your explanation! 

I misunderstood the definitions of okvs before, but it seems the collision probability is non-negligible even the input set is pretty large (2^20). 

So this feature does not affect psi due to the mask of vole.

**Comment by ladnir** [comment] 2024-12-24 16:36
Take a look here for more details https://eprint.iacr.org/2024/1989.pdf.

You can also close the issue

**Closed** 2024-12-24 16:49 UTC
